### ISSUE TITLE
Enable Hover Behavior

### ISSUE THREAD

**Issue by shahdivyank** [shahdivyank/r-parts#177]
<img width="1306" alt="image" src="https://github.com/shahdivyank/r-parts/assets/36285610/4fe92c68-3344-4608-9b33-d10b4a6542a0">

- when hovering over an item we need to enable some hover behavior to make it easier to show the current item

**Comment by bobbyyy57** [comment]
@lb-rodrigo 

on hover will display the second image of the item. example:

https://github.com/shahdivyank/r-parts/assets/72523111/0d88be21-f016-4bd1-99eb-6b3c1c14ca51
