### ISSUE TITLE
Create Navigation

### ISSUE THREAD

**Issue by shahdivyank** [shahdivyank/r-parts#2]
- Create a `Navigation.jsx` file under `components`
<img width="632" alt="image" src="https://user-images.githubusercontent.com/36285610/228793029-79322ddb-3b38-48a2-9cd8-285506b028b0.png">

**Comment by msclal** [comment]
@shahdivyank 

For the gear/user account/cart icons, do i install react icons for this or is there another icons library that we will use?
the react icons are very similar but they are not exactly the icons bobby used on figma
