### ISSUE TITLE
Create CheckoutTotal.jsx

### ISSUE THREAD

**Issue by shahdivyank** [shahdivyank/r-parts#20]
<img width="445" alt="image" src="https://user-images.githubusercontent.com/36285610/230582373-1fdcafbb-b5d4-4d11-93ff-31647ce14c2f.png">

- Place it in checkout.js

**Comment by msclal** [comment]
@mgolwalla 
checkout CartTotal.jsx
u need to probbaly set the width on line 6 to ```w-1/2``` or something
